//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CRUD_EF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CadastroEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CadastroEntities object using the connection string found in the 'CadastroEntities' section of the application configuration file.
        /// </summary>
        public CadastroEntities() : base("name=CadastroEntities", "CadastroEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CadastroEntities object.
        /// </summary>
        public CadastroEntities(string connectionString) : base(connectionString, "CadastroEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CadastroEntities object.
        /// </summary>
        public CadastroEntities(EntityConnection connection) : base(connection, "CadastroEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Produto> Produtos
        {
            get
            {
                if ((_Produtos == null))
                {
                    _Produtos = base.CreateObjectSet<Produto>("Produtos");
                }
                return _Produtos;
            }
        }
        private ObjectSet<Produto> _Produtos;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Produtos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProdutos(Produto produto)
        {
            base.AddObject("Produtos", produto);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CadastroModel", Name="Produto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Produto object.
        /// </summary>
        /// <param name="produtoId">Initial value of the produtoId property.</param>
        /// <param name="nomeProduto">Initial value of the nomeProduto property.</param>
        public static Produto CreateProduto(global::System.Int32 produtoId, global::System.String nomeProduto)
        {
            Produto produto = new Produto();
            produto.produtoId = produtoId;
            produto.nomeProduto = nomeProduto;
            return produto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 produtoId
        {
            get
            {
                return _produtoId;
            }
            set
            {
                if (_produtoId != value)
                {
                    OnprodutoIdChanging(value);
                    ReportPropertyChanging("produtoId");
                    _produtoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("produtoId");
                    OnprodutoIdChanged();
                }
            }
        }
        private global::System.Int32 _produtoId;
        partial void OnprodutoIdChanging(global::System.Int32 value);
        partial void OnprodutoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nomeProduto
        {
            get
            {
                return _nomeProduto;
            }
            set
            {
                OnnomeProdutoChanging(value);
                ReportPropertyChanging("nomeProduto");
                _nomeProduto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nomeProduto");
                OnnomeProdutoChanged();
            }
        }
        private global::System.String _nomeProduto;
        partial void OnnomeProdutoChanging(global::System.String value);
        partial void OnnomeProdutoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> categoriaid
        {
            get
            {
                return _categoriaid;
            }
            set
            {
                OncategoriaidChanging(value);
                ReportPropertyChanging("categoriaid");
                _categoriaid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("categoriaid");
                OncategoriaidChanged();
            }
        }
        private Nullable<global::System.Int32> _categoriaid;
        partial void OncategoriaidChanging(Nullable<global::System.Int32> value);
        partial void OncategoriaidChanged();

        #endregion
    
    }

    #endregion
    
}
